# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-24 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RmUsers',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('groupid', models.IntegerField()),
                ('enableuser', models.IntegerField()),
                ('uplimit', models.BigIntegerField()),
                ('downlimit', models.BigIntegerField()),
                ('comblimit', models.BigIntegerField()),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=8)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=500)),
                ('gpslat', models.DecimalField(decimal_places=14, max_digits=17)),
                ('gpslong', models.DecimalField(decimal_places=14, max_digits=17)),
                ('mac', models.CharField(max_length=17)),
                ('usemacauth', models.IntegerField()),
                ('expiration', models.DateTimeField()),
                ('uptimelimit', models.BigIntegerField()),
                ('srvid', models.IntegerField()),
                ('staticipcm', models.CharField(max_length=15)),
                ('staticipcpe', models.CharField(max_length=15)),
                ('ipmodecm', models.IntegerField()),
                ('ipmodecpe', models.IntegerField()),
                ('poolidcm', models.IntegerField()),
                ('poolidcpe', models.IntegerField()),
                ('createdon', models.DateField()),
                ('acctype', models.IntegerField()),
                ('credits', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cardfails', models.IntegerField()),
                ('createdby', models.CharField(max_length=64)),
                ('owner', models.CharField(max_length=64)),
                ('taxid', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
                ('maccm', models.CharField(max_length=17)),
                ('custattr', models.CharField(max_length=255)),
                ('warningsent', models.IntegerField()),
                ('verifycode', models.CharField(max_length=10)),
                ('verified', models.IntegerField()),
                ('selfreg', models.IntegerField()),
                ('verifyfails', models.IntegerField()),
                ('verifysentnum', models.IntegerField()),
                ('verifymobile', models.CharField(max_length=15)),
                ('contractid', models.CharField(max_length=50)),
                ('contractvalid', models.DateField()),
                ('actcode', models.CharField(max_length=60)),
                ('pswactsmsnum', models.IntegerField()),
                ('alertemail', models.IntegerField()),
                ('alertsms', models.IntegerField()),
                ('lang', models.CharField(max_length=30)),
                ('lastlogoff', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rm_users',
                'managed': False,
            },
        ),
    ]
